# Generated by Django 3.1.3 on 2020-11-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_photo', models.ImageField(upload_to='private/original_photos')),
                ('watermarked_photo', models.ImageField(upload_to='public/photos')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=80)),
                ('price', models.IntegerField()),
                ('wishes', models.IntegerField(default=0)),
            ],
        ),
    ]
