# Generated by Django 3.1.3 on 2020-11-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0002_auto_20201126_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='wishes',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='public/category_photos'),
        ),
    ]
